name: ci-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose stack
        run: docker-compose -f ../../docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run test suite
        run: docker exec control-node make test
